# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Quantitas Tourism Intelligence. Analizza, valuta e prendi decisione Data Driven
description: >- # this means to ignore newlines until "baseurl:"
  Il nostro team costruisce ad hoc per la tua DMO soluzioni e narrazioni integrate di dati per rispondere alle domande sul tuo territorio e sul mercato del turismo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: "it"
email: info@quantitas.it
twitter_username: QuantitasSrl
facebook_username: quantitas.it
linkedin_username: quantitas-srl

page-cta-eye-brown: da DMO a Smart Tourism Destination con Quantitas
page-cta-heading: Fai crescere la tua Destinazione con la <strong class="text-accent">Tourism Intelligence</strong>
page-cta-link: Inizia ora la trasformazione

clients:
  - path: /assets/images/clients/otrf.png
    alt: Logo di Osservatorio del Turismo Regionale Federato
  - path: /assets/images/clients/destination-verona-garda.png
    alt: Logo di Destination Verona Garda Foundation
  - path: /assets/images/clients/bologna-welcome.png
    alt: Logo di Bologna Welcome
  - path: /assets/images/clients/ticino-welcome.png
    alt: Logo di Ticino Welcome
  - path: /assets/images/clients/terre-alto-piemonte.png
    alt: Logo di Terre dell'Alto Piemonte
  - path: /assets/images/clients/distretto-dei-laghi.png
    alt: Logo di Distretto Turistico dei Laghi
  - path: /assets/images/clients/comune-cremona.png
    alt: Logo del Comune di Cremona
  - path: /assets/images/clients/dolomiti-bellunesi.png
    alt: Logo di Dolomiti Bellunesi
  - path: /assets/images/clients/g20-spiagge.png
    alt: Logo di G20 Spiagge Italiane
faqs:
  - question: Testo della domanda
    answer: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
      dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  - question: Testo della domanda
    answer: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
      dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  - question: Testo della domanda
    answer: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
      dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  - question: Testo della domanda
    answer: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
      dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  - question: Testo della domanda
    answer: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
      dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  - question: Testo della domanda
    answer: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
      dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  - question: Testo della domanda
    answer: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
      dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

debug: true # TODO remove in production

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - assets/js/script.webpack.js
  - assets/css/style.tailwind.css
  - tailwind.config.js
  - webpack.config.js
  - README.md
  - package.json
  - package-lock.json
  - .jekyll-cache/
  - assets/js/script.js.LICENSE.txt
